name: flutter_riverpod_base
description: A Starter project for flutter with riverpod and http preconfigured in architecture.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_dash: ^1.0.0
  google_fonts:
  animated_splash_screen: ^1.3.0
  pinput: ^3.0.1
  flutter_svg:
  flutter_rating_bar: ^4.0.1
  dotted_border: ^2.1.0

  #riverpod
  flutter_riverpod:
  fpdart:
  http:
  dotted_line: ^3.2.2
  ionicons: ^0.2.2

  go_router: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans-VariableFont_wght.ttf
